import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/header";
import Footer from "./components/footer";
import { ClerkProvider } from "@clerk/nextjs";
import Email from "./components/email";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      
        <link
          rel="stylesheet"
          href="https://cdn.snipcart.com/themes/v3.6.1/default/snipcart.css"
        />
        <script
          async
          src="https://cdn.snipcart.com/themes/v3.6.1/default/snipcart.js"
        ></script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
        <ClerkProvider>
        
          <NavBar />
          {children}
          <Email/>
          <Footer />
       
        </ClerkProvider>

 
        <div
          hidden
          id="snipcart"
          data-api-key="YjM4NDU5YzktYTdkZS00YzRkLWJjNzMtZDZlNTdjMGRhMDkyNjM4ODA3MzczNzQ3MTY5MDI2"
          data-config-modal-style="side"
        ></div>
      </body>
    </html>
  );
}
